#if !canImport(ObjectiveC)
import XCTest

extension EvangelizoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EvangelizoTests = [
        ("testCanGetReadingsOfTheDay", testCanGetReadingsOfTheDay),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EvangelizoTests.__allTests__EvangelizoTests),
    ]
}
#endif
