#if !canImport(ObjectiveC)
import XCTest

extension UsccbTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsccbTests = [
        ("testCanDownloadReadingsOfToday", testCanDownloadReadingsOfToday),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UsccbTests.__allTests__UsccbTests),
    ]
}
#endif
